### ISSUE TITLE
raylib folder name

### ISSUE THREAD

**Issue by 4FranJonas2** [LucioPiccioni/Sugaroids-Raylib#3]
is better for future optimizing o rework to leave the raylib folder name as default to know what version of the librarie is on the proyect.

**Comment by LucioPiccioni** [comment]
There is no need to make a folder 1 one PNG. I talk to the teacher.

**Comment by 4FranJonas2** [comment]
te confundiste de issue, aca te estoy mmarcando que el nombre la carpeta raylib lo dejes como default y no lo simplifiques, no es util no poder ver la version de raylib que esta usando el proyecto
