### ISSUE TITLE
SetFPS no esta recomendado

### ISSUE THREAD

**Issue by 4FranJonas2** [LucioPiccioni/Sugaroids-Raylib#5]
como parte de la consideracion sobre los variados tipos de computadoras que podrian reproducir tu juego, es mas recomnedado no setear los fps. de hacerlo podrias limitar la cantidad de personas que podrian disfrutar de tu juego y e perderian la experiencia

**Comment by LucioPiccioni** [comment]
Aunque dejar el juego sin un límite de FPS puede hacer que más computadoras lo ejecuten a mayor velocidad, establecer un límite tiene beneficios importantes para la experiencia del usuario y el rendimiento general. Sin un límite, el juego podría consumir recursos innecesariamente, lo que afectaría el rendimiento en sistemas menos potentes y podría hacer que el juego sobrecargue la CPU y la GPU en hardware más antiguo.

Además, no limitar los FPS puede causar problemas visuales como *screen tearing*, especialmente si el monitor del jugador no es compatible con altas tasas de cuadros. Al configurar un límite de FPS razonable, el juego funcionará de manera más uniforme y reducirá el riesgo de experiencias visuales deficientes o problemas de rendimiento en una variedad de equipos.

**Comment by LucioPiccioni** [comment]
Aunque dejar los FPS sin límite permite que algunos equipos corran el juego a su máximo, también puede hacer que otros dispositivos sufran con el rendimiento o consuman demasiados recursos. Poner un límite ayuda a evitar que el juego sobrecargue la computadora, manteniéndolo fluido en la mayoría de sistemas y previniendo problemas visuales como el *screen tearing*. Así, el juego se disfruta mejor en diferentes tipos de equipo sin comprometer la experiencia.
